export const actionTypes = {
  LOGIN: 'LOGIN',
 // REGISTER: 'REGISTER',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',
  CHANGE_STATUS: 'CHANGE_STATUS',
 // REGISTER_FAILED: 'REGISTER_FAILED',
 // REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  INFO_CHAT_USER: 'INFO_CHAT_USER'
}